# Generated by Django 6.0.2 on 2026-02-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.CharField(max_length=50, unique=True)),
                ("current_lat", models.FloatField()),
                ("current_lng", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DISPATCHED", "On Route"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="anomalyresult",
            name="ai_empathy_response",
        ),
        migrations.RemoveField(
            model_name="anomalyresult",
            name="detected_category",
        ),
        migrations.RemoveField(
            model_name="healthlog",
            name="local_weather",
        ),
        migrations.RemoveField(
            model_name="medicalfacility",
            name="address",
        ),
        migrations.RemoveField(
            model_name="medicalfacility",
            name="current_capacity_status",
        ),
        migrations.AddField(
            model_name="anomalyresult",
            name="ai_followup_question",
            field=models.TextField(
                default="No signal detected",
                help_text="Safe, empathetic context-gathering question.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anomalyresult",
            name="domain",
            field=models.CharField(
                choices=[
                    ("METABOLIC", "Metabolic Risk"),
                    ("CARDIO", "Cardiovascular"),
                    ("PSYCHO", "Psycho-Emotional"),
                    ("NEURO", "Neurological"),
                    ("NONE", "Stable"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="anomalyresult",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthlog",
            name="bmi_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthlog",
            name="depression_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthlog",
            name="health_perception",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalfacility",
            name="capacity_status",
            field=models.CharField(
                choices=[("LOW", "Low Wait"), ("MED", "Medium"), ("HIGH", "Crowded")],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="medicalfacility",
            name="category",
            field=models.CharField(
                choices=[
                    ("METABOLIC", "Metabolic Risk"),
                    ("CARDIO", "Cardiovascular"),
                    ("PSYCHO", "Psycho-Emotional"),
                    ("NEURO", "Neurological"),
                    ("NONE", "Stable"),
                ],
                default="No signal detected",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicalfacility",
            name="is_certified",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="log",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="core.healthlog",
            ),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="risk_score",
            field=models.FloatField(help_text="Anomaly score (0.0 - 1.0)"),
        ),
        migrations.AlterField(
            model_name="anomalyresult",
            name="signal_explanation",
            field=models.TextField(help_text="The 'Why' behind the flag."),
        ),
        migrations.AlterField(
            model_name="healthlog",
            name="raw_text",
            field=models.TextField(
                help_text="Context-aware diary input for anomaly detection."
            ),
        ),
        migrations.DeleteModel(
            name="HealingCircle",
        ),
    ]
